export const auraColourTokens = [
  "--lumeo-ink-950",
  "--lumeo-ink-900",
  "--lumeo-ink-850",
  "--lumeo-ink-800",
  "--lumeo-ink-750",
  "--lumeo-paper-50",
  "--lumeo-paper-100",
  "--lumeo-paper-200",
  "--lumeo-paper-400",
  "--lumeo-paper-600",
  "--lumeo-seal-400",
  "--lumeo-seal-500",
  "--lumeo-seal-600",
  "--lumeo-seal-700",
  "--lumeo-gold-300",
  "--lumeo-gold-400",
  "--lumeo-gold-500",
  "--lumeo-aura-300",
  "--lumeo-aura-400",
  "--lumeo-aura-500",
] as const;

export const auraSurfaceTokens = [
  "--surface-canvas",
  "--surface-base",
  "--surface-raised",
  "--surface-elevated",
  "--surface-floating",
  "--surface-input",
  "--surface-overlay",
] as const;

export const auraMotionTokens = [
  "--motion-instant",
  "--motion-fast",
  "--motion-standard",
  "--motion-expressive",
  "--motion-entrance",
  "--ease-standard",
  "--ease-enter",
  "--ease-exit",
  "--ease-spring-soft",
] as const;

export const auraComponentFoundations = [
  "AuraButton",
  "AuraIconButton",
  "AuraCard",
  "AuraPanel",
  "AuraSurface",
  "AuraInput",
  "AuraTextarea",
  "AuraSelect",
  "AuraSwitch",
  "AuraCheckbox",
  "AuraRadioGroup",
  "AuraSegmentedControl",
  "AuraTabs",
  "AuraBadge",
  "AuraStatus",
  "AuraTooltip",
  "AuraPopover",
  "AuraDropdown",
  "AuraDialog",
  "AuraDrawer",
  "AuraToast",
  "AuraProgress",
  "AuraSkeleton",
  "AuraEmptyState",
  "AuraNotice",
  "AuraMetric",
  "AuraTable",
  "AuraPageHeader",
  "AuraSectionHeader",
  "AuraBreadcrumbs",
  "AuraSearchInput",
  "AuraCommandMenu",
  "AuraUploadSurface",
  "AuraFileCard",
  "AuraResultCard",
] as const;

export type AuraComponentFoundation = (typeof auraComponentFoundations)[number];
